### ISSUE TITLE
Kadnode won't respond after multiple lookup

### ISSUE THREAD

**Issue by GaetanCathelain** [mwarning/KadNode#67] opened 2017-04-14 09:30 UTC
Hi,

I've been looking a bit into your software for the last couple of days and I wanted to build a quick "benchmark" program in golang to evaluate what latency we can expect. To do so I announced a several node names with --value id (500 to be precise) on a node, an tried to resolve them on another machine.

The thing is that after 60~ successful lookups on the client trying to resolve these, Kadnode only throws "Some error occured.", either directly through Kadnode's console or via Kadnode-ctl.

The benchmark I do in go is pretty much straight forward, I mimic Kadnode-ctl by sending UDP messages to the running instance of Kadnode, throwing "lookup Xmynode.p2p" every 100ms to Kadnode and when Kadnode replies with an IP adress, I register the time it took to look it up.

Any idea where this might come from ?

**Comment by mwarning** [comment] 2017-04-14 13:52
hi @GaetanCathelain,

It looks like the maximum amount of concurrent searches was exhausted.
The current maximum is set to 64. This limit is artificial (MAX_SEARCHES)
It might be a good idea to get rid of this limit.

**Comment by mwarning** [comment] 2017-04-14 14:07
Anyway, KadNode haven't gotten the care it deserves in the last few years.

**Comment by GaetanCathelain** [comment] 2017-04-14 15:06
Thank you for your response, i'll try without this limit ! 

I was truely surprised that this projet didn't bring more contributors honestly. It might be due to performance issue, which i'm trying to estimate :)

Anyway I didn't get deep into the code but from what I've seen Kadnode has a lot of potential ! Do you know if any other DHT have been implemented since that would be worth looking into ?

**Comment by mwarning** [comment] 2017-04-14 19:30
I remember https://github.com/torrentkino/torrentkino. But there are certainly more. I have heard about a few, those were mostly huge (in code size) compared to KadNode.

If I had the time, I would make KadNode simpler and faster (see https://github.com/mwarning/KadNode/wiki for a todo list).

I also see a lot of potential. But a problem I have trouble with to figure out, is how to move out authentication to applications. I think that is the right thing to do.

Think of a browser where we enter some domain and the Browser does the authentication with its keychain. DNS only provides the IP address. And most programs have it's own way to authenticate the target.

When KadNode tries to resolve some key/domain, it get's multiple possible IP-Addresses.
But usually it can only forward one IP-address to the application - which might be the wrong one. But we do not know if that is the expected IP address since we lack a back channel mechanism for an application to tell KadNode that the IP-Address failed authentication.
(... and the peer might be malicious and need to be dropped).

Or maybe KadNode can use the keychain that browsers use (those can be managed/edited by the user). But I fear that the dependencies might blow up KadNode.

@axxName: this might interest you ^ :-)

**Comment by mwarning** [comment] 2017-04-14 19:39
There is mbedtls (embedded) and openssl (desktop), if we can untilize the browser toolchain (and also add custom entries) to do authentication only, then this would be awesome.

**Comment by GaetanCathelain** [comment] 2017-04-14 20:00
From what I understand, you would like to orient KadNode to a browser optimized DNS, but the thing is that DNS are crazy fast to bring the user a good experience, while on KadNode from what i've seen response time is closer to 10-30s. 

I've looked into the todo list and saw that it'd be better to find another DHT. From my experience the fastest torrent client I used is rTorrent by far, but it looks like it uses trackers as a primary peer source and some DHT as backup.

I'm new to the DHTs but this is an interesting subject and although there are many papers about using them as a DNS, there isn't a lot of real world implementations.

**Comment by mwarning** [comment] 2017-04-14 22:21
I like to have some decentralized DNS that is not limited to be used for Browsers, but any application. The problem is to have a common certificate store, I need to evaluate what kind of storage browsers use and how own entries can be made.

It would be very nice to have a chat client where you can add some contact by domain+certificate. The chat-program can add the certificate to the certificate storage (probably the same the browser uses, that is how I ended up talking about browsers..).

An alternative would be to use the pgp key storage, but I do not see a good chance to leverage that for an embedded system like wifi routers. There is already emdtls.

As for a faster DHT, I do not know what rTorrent uses; but it might be hard to verify its speed by simply using rTorrent. The paper in the wiki claims a speedup up to ~1sec for the type of DHT we use.

**Comment by mwarning** [comment] 2017-09-01 20:59
I will close this issue as the code has been undergone heavy refactoring.

**Closed by mwarning** 2017-09-01 20:59 UTC
