### ISSUE TITLE
PEERFILE: Cannot resolve address

### ISSUE THREAD

**Issue by atommixz** [mwarning/KadNode#46] opened 2016-08-15 03:03 UTC
```
$ ./kadnode --config ./kadnode.conf                                                05:54 15-08-16
(I) Starting KadNode v1.0.0 ( lpd auth cmd nss dns )
(I) Node ID: cd89a081cdbd5f4049f264563d83d791c70875c4
(I) IP Mode: IPv6
(I) Run Mode: Foreground
(I) Configuration File: './kadnode.conf'
(I) Verbosity: verbose
(I) Query TLD: .p2p
(I) Peer File: /home/atommixz/build/kadnode/build/peers.txt
(I) LPD Address: ff15::efc0:988f
(I) KAD: Bind to [::]:6881
(I) LPD: Bind to [::]:6771
(I) DNS: Bind to [::1]:3535
(I) NSS: Bind to [::1]:4053
(I) CMD: Bind to [::1]:1700
Press Enter for help.
(W) LPD: Failed to join multicast group on enp4s0: Address already in use
(W) LPD: Failed to join multicast group on enp4s0: Address already in use
(I) LPD: No peers known. Joined multicast group.
(I) LPD: Send multicast message to find nodes.
(W) PEERFILE: Cannot resolve address: 'bttracker.debian.org:6881'
(W) PEERFILE: Cannot resolve address: 'router.bittorrent.com:6881'
(W) PEERFILE: Cannot resolve address: 'router.utorrent.com:6881'
(W) PEERFILE: Cannot resolve address: 'h.hypertracker.ru'
(I) PEERFILE: Imported 0 peers from: '/home/atommixz/build/kadnode/build/peers.txt'
```

what can I do wrong? I have this msg on two different machines and all this hosts resolves for me. I try different ip mode but I have same issue.

**Comment by mwarning** [comment] 2016-08-15 08:10
It looks like a bug, I will fix it later. Thanks for reporting.

**Comment by atommixz** [comment] 2016-08-15 13:29
version from git

**Comment by mwarning** [comment] 2016-08-15 20:19
@atommixz I figured out that the error is intentional. The problem is, that resolving router.utorrent.com would feed the KadNode itself the address to be resolved.
For that reason, only IP addresses are allowed.

But I think that problem can be circumvented.

**Comment by mwarning** [comment] 2016-08-16 18:42
@atommixz I changed the code. It should work now the way you use it.

**Closed by mwarning** 2016-08-16 18:42 UTC

**Comment by atommixz** [comment] 2016-08-16 18:52
(W) PEERFILE: Cannot resolve address: 'router.bittorrent.com:6881'
(W) PEERFILE: Cannot resolve address: 'router.utorrent.com:6881'
(I) PEERFILE: Imported 2 peers from: '/home/atommixz/build/kadnode/build/peers.txt'

I'm not really understand what is mean ipv6 mode. but i think it should resolve and connect to any tracker addresses.

**Comment by mwarning** [comment] 2016-08-16 19:18
KadNode either uses IPv4 or IPv6 (but not both). I assume you use --mode ipv6 and  router.bittorrent.com / router.utorrent.com probably do not resolve to IPv6 addresses.
