### ISSUE TITLE
No Answer on dns Port

### ISSUE THREAD

**Issue by stargieg** [mwarning/KadNode#45] opened 2016-06-23 18:26 UTC
dig AAAA -p 3535 jabbahood.p2p @::1 ends up with time out.
the sendto() in https://github.com/mwarning/KadNode/blob/master/src/ext-dns.c#L622 return "invalid argument" because of wrong IP addr len.
Patch: https://github.com/stargieg/KadNode/commit/f0f7ea7289f8252f78afec61ef47b5a6c8ab7889

**Comment by mwarning** [comment] 2016-06-23 20:32
I have never encountered an issue where the addrlen field is too big. And I cannot reproduce it at my end.
Anyway, feel free to make a merge request for this one, and i will merge it. :-)

**Comment by mwarning** [comment] 2016-06-26 21:34
edit: I cherry-picked this one and will push this one with the local peer discovery stuff.

**Comment by mwarning** [comment] 2017-09-01 21:02
the code has been changed a lot so far. I hope your issue has been fixed by now..

**Closed by mwarning** 2017-09-01 21:02 UTC
